# -*- coding: utf-8 -*-
"""Tubes_Visdat_Stock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KHP1Qm1mfXAnQppfk2EDhZog1yPbNHjj
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
from sklearn import preprocessing
from matplotlib import pyplot as plt
# %matplotlib inline
from bokeh.models import ColumnDataSource
from bokeh.models import HoverTool
from bokeh.io import output_notebook,output_file
from bokeh.plotting import figure, show
from bokeh.layouts import gridplot
from bokeh.models.widgets import Tabs, Panel
import bokeh.plotting
bokeh.io.output_notebook()
import matplotlib.dates as mdates

data = pd.read_csv("/content/all_stocks_5yr.csv", sep=",", parse_dates=['date'])
data

data_1 = data[['date','Name','close']]
al = data_1[data_1['Name'] == 'AAL']
av = data_1[data_1['Name'] == 'ABBV']
zs = data_1[data_1['Name'] == 'ZTS']

al_cl = ColumnDataSource(al)
av_cl = ColumnDataSource(av)
zs_cl = ColumnDataSource(zs)

tooltips = [('Name', '@Name'), ('close', '$y{0.2f}')]

adjclose = figure(x_axis_type='datetime', plot_height=400, plot_width=800, title='Harga Penutupan dari Ticker Saham', 
                 x_axis_label='Date', y_axis_label='Harga Penutupan', tooltips = tooltips)

adjclose.line('date', 'close', color='gray', legend_label='AAL', source=al_cl)
adjclose.line('date', 'close', color='green', legend_label='ABBV', source=av_cl)
adjclose.line('date', 'close', color='blue', legend_label='ZTS', source=zs_cl)

adjclose.legend.location = 'center_right'

#show(adjclose)

adj1 = data.loc[data.Name == 'AAL']
adj2 = data.loc[data.Name == 'ABBV']
adj3 = data.loc[data.Name == 'ZTS']

Volume1 = ColumnDataSource(adj1)
Volume2 = ColumnDataSource(adj2)
Volume3= ColumnDataSource(adj3)

pilih_tools = ['box_select', 'lasso_select', 'poly_select', 'tap', 'reset']

newplot = figure(plot_height=400,
             x_axis_type="datetime",
             x_axis_label='Date',
             y_axis_label='Jumlah Transaksi',
             plot_width=600,
             title='Jumlah Transaksi',
             toolbar_location='below',
             tools=pilih_tools)

satu = newplot.line(x='date',
           y='volume',
           alpha=0.5,
           source=Volume1,
           color="navy",
           selection_color='deepskyblue',
           nonselection_color='lightgray',
           nonselection_alpha=0.3,
           legend_label='AAL')

dua = newplot.line(x='date',
           y='volume',
           alpha=0.5,
           source=Volume3,
           color="firebrick",
           selection_color='deepskyblue',
           nonselection_color='lightgray',
           nonselection_alpha=0.3,
           legend_label='ABBV')

tiga = newplot.line(x='date',
           y='volume',
           alpha=0.5,
           source=Volume2,
           color="olive",
           selection_color='deepskyblue',
           nonselection_color='lightgray',
           nonselection_alpha=0.3,
           legend_label='ZTS' )

tooltips = [
            ( 'Name', '@Name'      ),
            ( 'volume',  '@{volume}' ), 
        
           ]

newplot.add_tools(HoverTool(tooltips=tooltips))
#show(newplot)

data_2 = data[['date','open','Name']]
day1 = data_2.loc[data_2.Name == 'AAL']
day2 = data_2.loc[data_2.Name == 'ABBV']
day3 = data_2.loc[data_2.Name == 'ZTS']

dpc1 = ColumnDataSource(day1)
dpc2 = ColumnDataSource(day2)
dpc3 = ColumnDataSource(day3)

pilihan_tools = ['box_select', 'lasso_select', 'poly_select', 'tap', 'reset']

newplot2 = figure(plot_height=400,
             x_axis_type="datetime",
             x_axis_label='Date',
             y_axis_label='Persentase Harga Saham',
             plot_width=600,
             title='Persentase Harga Saham	',
             toolbar_location='below',
             tools=pilihan_tools)

satu = newplot2.line(x='date',
           y='open',
           alpha=0.5,
           source=dpc1,
           color="navy",
           selection_color='deepskyblue',
           nonselection_color='lightgray',
           nonselection_alpha=0.3,
           legend_label='AAL')

dua = newplot2.line(x='date',
           y='open',
           alpha=0.5,
           source=dpc3,
           color="firebrick",
           selection_color='deepskyblue',
           nonselection_color='lightgray',
           nonselection_alpha=0.3,
           legend_label='ABBV')

tiga = newplot2.line(x='date',
           y='open',
           alpha=0.5,
           source=dpc2,
           color="olive",
           selection_color='deepskyblue',
           nonselection_color='lightgray',
           nonselection_alpha=0.3,
           legend_label='ZTS')

tooltips = [
            ( 'Name', '@Name'      ),
            ( 'open',  '@open' ),
        
           ]

newplot2.add_tools(HoverTool(tooltips=tooltips))

#show(newplot2)

Close = Panel(child=adjclose, title='Adj close')
Volume = Panel(child=newplot, title='Jumlah Transaksi')
Open = Panel(child=newplot2, title='Persentase Harga Saham')
tabs = Tabs(tabs=[Close, Volume, Open])

adjclose.legend.click_policy="hide"
newplot.legend.click_policy="hide"
newplot2.legend.click_policy="hide"

#output_file('stock_market_5yr.html')
show(tabs)